### ISSUE TITLE
project name is wrong

### ISSUE THREAD

**Issue by ogta** [barankurtulusozan/Nedir#2]
Can u fix it ? meraklina to meraklisina  :)

**Comment by barankurtulusozan** [comment]
Thank you for the reminder =)

**Comment by ogta** [comment]
You are welcome :)

**Comment by arslanbilal** [comment]
if it is possible, naming the project that reminding in people memory. Name is little(!) long. What do you think @barankurtulusozan ?

**Comment by barankurtulusozan** [comment]
what should it be? If you have an advice i would be glad changing the project name.

**Comment by arslanbilal** [comment]
Firstly, I don't think this multi language is good choice for repository name. 
After some time consuming for this, I recommend you to change with these:

##### computer-science-articles

##### article-about-programming

##### computer-programming-articles

##### article-in-programming etc
